server:
  port: 8080
  error:
    whitelabel:
      enabled: false
# logging settings
logging:
  level:
    root: info
# roman number unit mapping
romanNumberUnits:
  M:
    -
    - M
    - MM
    - MMM
  C:
    -
    - C
    - CC
    - CCC
    - CD
    - D
    - DC
    - DCC
    - DCCC
    - CM
  X:
    -
    - X
    - XX
    - XXX
    - XL
    - L
    - LX
    - LXX
    - LXXX
    - XC
  I:
    -
    - I
    - II
    - III
    - IV
    - V
    - VI
    - VII
    - VIII
    - IX
